grain-lang/grain-language-server

editor-extensions/vscode/client/src/CodeLensProvider.ts, editor-extensions/vscode/client/src/extension.ts, editor-extensions/vscode/package.json, editor-extensions/vscode/server/src/server.ts
Adds support for per-statement code lenses.
Breaking change as it requires the matching new LSP mode changes to the grainc compiler lsp mode.  This has been turned into generic JSON now so is more flexible for future changes.
=> Support per-statement code lenses

.gitignore, editor-extensions/vscode/client/src/extension.ts, editor-extensions/vscode/package.json, editor-extensions/vscode/server/src/server.ts, editor-extensions/vscode/syntaxes/generate-grain-type.js
This PR adds a new grammar that highlights Grain types, to be used with tooling. It can be used by supplying `language: 'grain-type'`.
In the future, we could optimize this by looking at the `patterns` key and recursively only keeping values in the repository that are used, but that's complex and probably not necessary.
With this, we probably don't need #32.
=> feat: Add specific grain-type grammar

editor-extensions/vscode/syntaxes/grain.json
This adds support for constants of the form `_FOO`. Also did some refactoring so this wouldn't have to be done in multiple places.
=> Add syntax highlighting for constants

editor-extensions/vscode/syntaxes/grain.json
Enum variants are used like functions in Grain, so `entity.name.function` is a better scope to apply than `support.type`.
=> Better scope for enum variants

editor-extensions/vscode/syntaxes/grain.json
Closes #6.
From our string tests:
=> Highlight extended string escapes

editor-extensions/vscode/syntaxes/grain.json
We haven't used this keyword for some time, and it breaks highlighting for valid uses of `and` as an identifier.
=> chore: clean up 'and' keyword

editor-extensions/vscode/package.json, editor-extensions/vscode/server/src/server.ts
When trying to use the Packaged Grain binaries as the LSP driver on Windows, I found a bunch of issues.
1. We don't want to append `.cmd` to the filename
2. We need to capitalize the drive letter otherwise it crashes
3. CRLF line feeds screw up the LSP line numbers
This fixes or paves over those issues.
=> Fixes to get Packaged Grain working with Windows

editor-extensions/vscode/syntaxes/grain.json
Fixes #53 
Also simplified this into a single rule.
=> fix: Floating-point number syntax highlighting

editor-extensions/vscode/syntaxes/grain.json
The diff looks really weird, but I just swapped the order of these two rules. I broke this with my last change 🙈 
I've looked into adding tests for the grammar previously, and now I've added an issue for it in #57.
=> fix: rational highlighting

editor-extensions/vscode/package.json
I think we missed this in the cleanup.
=> fix: No longer recommend \n for grain files

editor-extensions/vscode/client/src/GrainDocCompletionProvider.ts, editor-extensions/vscode/client/src/extension.ts
Almost a direct ripoff of the JsDoc implementation in the official vscode typescript extension. This can be improved to automatically fill out the `@param` and `@returns` in the future, but I just want it to auto complete the comment start/end right now.
=> feat: Add completions for Grain Doc comments

editor-extensions/vscode/syntaxes/grain.json
This makes storage tokens like `let` always highlight as a storage token, and not randomly as a control token.
=> fix: proper token types for storage keywords

editor-extensions/vscode/language-configuration.json
This uses a technique from https://github.com/kevb34ns/auto-comment-blocks to continue adding ` * ` when you hit return within a codeblock (thanks @marcusroberts for linking that extension previously).
=> feat(docblock): Continue to add * inside doc comments after return

editor-extensions/vscode/.npmrc, editor-extensions/vscode/package.json
All my usage of the `npm` command shuts off package-lock, so we should have an npmrc to enable it.
I also added a package command I've been using for my development workflow.
=> chore: Fix some nits

editor-extensions/vscode/client/src/extension.ts
Testing this on windows and it failed to work because the pattern wasn't a valid glob. (Yes, this also means that their multi-server example doesn't work correctly on Windows either).
=> Fix glob pattern on windows

editor-extensions/vscode/package-lock.json, editor-extensions/vscode/package.json, editor-extensions/vscode/src/extension.ts, editor-extensions/vscode/tsconfig.json
Closes #48
Closes #88 
This uses the `which` package from npm to locate grain executables within a user's path. I found a weird edge case in testing on Windows related to capitalized `.EXE` that I also "fixed" with a workaround.
=> feat: Search for a variety of grain CLIs in PATH

editor-extensions/vscode/package.json, editor-extensions/vscode/src/extension.ts
Closes #50
Closes #112 
This replaces the `grainfind.js` workaround with an option to specify flags passed to `grain lsp`. I tested this by changing `cliPath` to my local pkg executable, which outputs the stdlib into `./target/`, and then setting `cliFlags` to `--stdlib /abs/path/to/grain/stdlib` and verifying that it output the wasm files into the stdlib inside of grain.
=> feat!: Replace grainfind with cliFlags setting

editor-extensions/vscode/src/extension.ts
Marcus and I noticed that the LSP was being spammed with messages. I traced it down to this code path and found that we were spinning up an LSP server to handle the `output:` scheme, which we don't want to do, since those are sent by our LSP.
=> fix: Avoid handling output scheme messages

editor-extensions/vscode/package-lock.json, editor-extensions/vscode/package.json
This is currently in the testing phase for me (locally), but I think we **need** to ship this with the vscode extension due to out-of-order messages.
This version solves https://github.com/microsoft/vscode-languageserver-node/issues/968
=> chore: Upgrade to beta of vscode-languageclient

editor-extensions/vscode/syntaxes/grain.json
=> fix: Properly highlight true/false in pattern matching

editor-extensions/vscode/syntaxes/grain.json
Also made it highlight invalid ones.
Closes #73
=> fix: Only highlight valid string escapes

editor-extensions/vscode/icons/grain_shorthand_color.svg
This PR adjusts the icon size to better match other vscode icons. 
Before:
After:
=> fix: Adjust icon size

editor-extensions/vscode/syntaxes/grain.json
Here's an example, although I don't know if it's helpful if you're not using my same color theme:
=> fix: Highlight match keyword correctly

editor-extensions/vscode/syntaxes/grain.json
Will also support future extensions:
=> fix: Highlight module scoped types properly

editor-extensions/vscode/src/extension.ts
Events + promises are terrible. This implements a really naive mutex around our config change event handler so we don't create multiple clients when config changes.
=> fix: Add naive mutex around config change events

editor-extensions/vscode/syntaxes/grain.json
=> fix: Correctly highlight function type annotations in type vectors

editor-extensions/vscode/syntaxes/grain.json
Smoke test from the Grain test suite:
Closes #144 
Closes #145
=> feat: Support custom operators

editor-extensions/vscode/syntaxes/grain.json
I think when the parser was rewritten for graindoc it removed the ability todo `@since: next` this pr makes the syntax highlighting reflect that is no longer valid.
=> chore: remove graindoc `next` from highlighting

editor-extensions/vscode/syntaxes/grain.json
I accidentally closed my other pr, when I deleted my fork, reopening from my new fork.
Closes: #154
=> feat: Add support for new float syntax

editor-extensions/vscode/syntaxes/grain.json
=> feat: Support and keyword for data types

editor-extensions/vscode/syntaxes/grain.json
I didn't realize this was the only place it was wrong. I would have just done it in the other PR. Such is life.
=> fix: Use consistent scope for type variables

editor-extensions/vscode/package.json, editor-extensions/vscode/src/GrainErrorHandler.ts, editor-extensions/vscode/src/extension.ts
This adds a languageStatusItem to the vscode extension [VSCODE Status Item](https://code.visualstudio.com/api/ux-guidelines/status-bar) specifically this provides a place for us to list the grain extension commands and display stats about the server.
This pr also contributes a new `openOutput` command which opens the grain extension output window.
The statusBar item currently only shows an error severity when the lsp crashes out. But we can extend the functionality in the future similar to how rescript tracks status [here](https://github.com/rescript-lang/rescript-vscode/blob/8849a583855d85c199af617af4dac18fd1de23da/client/src/extension.ts#L151C45-L151C64) and have it show things such as if the lsp is busy during formatting.
=> feat(vscode): Add Language Status Item
