syntaxes/grain.json

Support let mutable and mutable record fields

---

syntaxes/grain.json

Better highlighting for type annotations

---

syntaxes/grain.json

Support match guards

---

syntaxes/grain.json

Support constant patterns

---

language-configuration.json
syntaxes/grain.json

Adds support for https://github.com/grain-lang/grain/pull/389.

Support new comment syntax

---

editor-extensions/vscode/syntaxes/grain.json

Adds support for https://github.com/grain-lang/grain/pull/394.

Support new record/enum syntax

---

editor-extensions/vscode/server/src/server.ts

Fixes for #19 - Please let me know if you'd want any of this done differently. I was mostly just trying to get Windows working and didn't think about the architecture of the plugin at all.

fix: handle filepaths & cmd file like Grain expects on Windows

---

editor-extensions/vscode/syntaxes/grain.json

fix: Syntax highlighting for and bindings

---

editor-extensions/vscode/syntaxes/grain.json

Fix highlighting of tuple types

---

.github/workflows/publish.yml
editor-extensions/vscode/package-lock.json
editor-extensions/vscode/package.json

Relies on #28 
Following https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions - I set up a script for publishing. We'll need to add the publish token in GH token store.

GitHub Action for publish

---

editor-extensions/vscode/syntaxes/grain.json

feat: Add syntax support for for loops

---

editor-extensions/vscode/.prettierignore
editor-extensions/vscode/CHANGELOG.md
editor-extensions/vscode/package.json
editor-extensions/vscode/server/src/server.ts
editor-extensions/vscode/syntaxes/grain.json

chore: run prettier on master

---

editor-extensions/vscode/server/src/server.ts

Return code warnings generated by the compiler and display to the user
Fixes #52

feat: parse warnings from code returned from LSP

---

.github/workflows/build.yml

chore: Check formatting on CI

---

editor-extensions/vscode/server/src/server.ts

fix: remove the block on CRLF format

---

editor-extensions/vscode/server/src/server.ts

This PR includes a few fixes to get LSP working in neovim or other non-vscode editors.

fix: enable neovim

---

editor-extensions/vscode/server/src/server.ts

chore: Fixed formatting

---

editor-extensions/vscode/server/src/server.ts

Check if running on Windows and add .exe or .cmd as needed
Also use the Settings setting for the executable name

fix: Correct the executable path

---

editor-extensions/vscode/client/src/extension.ts

Enable/disable LSP
Change the Grain cli executable

Use the VSCode configs client site

---

editor-extensions/vscode/client/src/extension.ts

Some further cleanup of the new LSP changes. We should be tracking all the disposables we are creating. I also noticed that we weren't doing some stuff the same way that the workspace example was doing.

Further LSP refactor

---

editor-extensions/vscode/syntaxes/grain.json

feat: Support or-pattern and alias syntax

---

editor-extensions/vscode/syntaxes/grain.json

feat: Add bigint syntax highlighting

---

editor-extensions/vscode/syntaxes/grain.json

feat: Graindoc highlighting

---

editor-extensions/vscode/syntaxes/grain.json

fix: Correctly highlight block comments

---

editor-extensions/vscode/syntaxes/grain.json

Waiting on Infinity And NaN syntax pr in main grain repo
Closes: #141

feat: Add `Infinity` And `NaN` Highlighting

---

editor-extensions/vscode/syntaxes/grain.json

feat: Support short and unsigned ints

---

editor-extensions/vscode/syntaxes/grain.json

This does not remove support for the old system, as that will come later.

feat: Support new module system

---

editor-extensions/vscode/syntaxes/grain.json

feat: Update scoping operator syntax

---

editor-extensions/vscode/syntaxes/grain.json

feat: Update module include syntax

---

editor-extensions/vscode/syntaxes/grain.json

feat: Exception highlighting

---

editor-extensions/vscode/syntaxes/grain.json

feat: Support @throws graindoc
